# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TogglSync < Formula
  desc "Toggl sync util"
  homepage "https://github.com/timemate"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.3/toggl-sync-0.2.3-darwin-amd64.tar.gz"
      sha256 "dacbe7670537fafe4e31abe6f794e1a4281a80fcd3643a2afad2421485113c37"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.3/toggl-sync-0.2.3-darwin-arm64.tar.gz"
      sha256 "136c2b222921bed88f992a93a5a242c00e60ab5d7b7cc89607e3d701adfae890"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.3/toggl-sync-0.2.3-linux-arm64.tar.gz"
      sha256 "0b3ad2507d46dbaf7c14da51bf33a55453249b5305c2bc4b1b66362bac385e26"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.3/toggl-sync-0.2.3-linux-amd64.tar.gz"
      sha256 "c31c7772a5c373045f81535252537b73c8b231d20ee1ba086ae8f95ea89225ba"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.3/toggl-sync-0.2.3-linux-armv6.tar.gz"
      sha256 "b258f8514ca597528613ec48e0d9098d2607a7e2f644c0a27c0cdbc36f43c88a"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/toggl-sync --version"
  end
end
