# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TogglSync < Formula
  desc "Toggl sync util"
  homepage "https://github.com/timemate"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.5/toggl-sync-0.2.5-darwin-amd64.tar.gz"
      sha256 "14a53af7a485edc980d8ec085325de3501670b8fa03dac9869be7ced5054a63b"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.5/toggl-sync-0.2.5-darwin-arm64.tar.gz"
      sha256 "7034000b77cb2ddc856860d02a779fef83f5916bd1c4bb5a0dc53d789d1681b2"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.5/toggl-sync-0.2.5-linux-arm64.tar.gz"
      sha256 "9f1bd5d071b3571ce2dedc9ed4b7be2da2859c1c2ebb9327022c981fa7711898"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.5/toggl-sync-0.2.5-linux-armv6.tar.gz"
      sha256 "2846a4bf88827d7e45e2e80c73a7f23f640c8cc6e680b33192854ffdb094683b"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/timemate/toggl-sync/releases/download/v0.2.5/toggl-sync-0.2.5-linux-amd64.tar.gz"
      sha256 "23bb6aae7ac4aa215af8e527f9df68f8a6d417ca45ac8524485efb9abba0f5c4"

      def install
        bin.install "toggl-sync"
        output = Utils.popen_read("#{bin}/toggl-sync completion bash")
        (bash_completion/"toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion zsh")
        (zsh_completion/"_toggl-sync").write output
        output = Utils.popen_read("#{bin}/toggl-sync completion fish")
        (fish_completion/"toggl-sync.fish").write output
        prefix.install_metafiles
      end
    end
  end

  plist_options startup: false

  def plist
    <<~EOS
      <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
    <string>#{bin}/toggl-sync</string>
    <string>sync</string>
    <string>--service</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>#{var}/log/toggl-sync/toggl-sync.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/toggl-sync/toggl-sync.log</string>
  </dict>
</plist>

    EOS
  end

  test do
    system "#{bin}/toggl-sync --version"
  end
end
